version: '3.7'
services:
  pyxmobile:
    image: postgres:lastest
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=mobile
    volumes:
      - pgdata:/data/postgres
  mobile:
    build: .
    container_name: api
    restart: always
    ports:
      - 3435:3435
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - pyxmobile
    depends_on:
      - pyxmobile

volumes:
  pgdata:
    driver: local
